crudp/crudapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "app"

urlpatterns = [
    path('',views.index,name="index"),
    path('employeer/show/',views.show,name="show"),
    path('employeer/update/<int:id>',views.update,name="update"),
    path('employeer/delete/<int:id>/',views.delete,name="delete"),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

crudp/crudp/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('crudapp.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

crudp/crudapp/models.py
from django.db import models

# Create your models here.
class Employeer(models.Model):
    eid = models.CharField(max_length = 20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)
    eimage = models.ImageField(upload_to='epics')


    class Meta:
        db_table = "employeer"
    
    

crudp/crudapp/forms.py
from django import forms
from . import models

class EmployeerForm(forms.ModelForm):
    class Meta:
        model = models.Employeer
        fields = '__all__'

        

crudp/crudapp/views.py
from django.shortcuts import render , HttpResponse , HttpResponseRedirect
from django.shortcuts import reverse
from . import forms
from . import models
# Create your views here.
def index(request):

    if request.method == "POST":
        form = forms.EmployeerForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse('app:show'))

            except:
                print(form.errors)
    else:
        form = forms.EmployeerForm()
    return render(request,'employeer.html',{'form':form})
    
def show(request):
    employeers = models.Employeer.objects.all()
    return render(request,'show.html',{'employeers':employeers})

def update(request,id):

    employeer = models.Employeer.objects.get(id=id)

    if request.method == "POST":
        form = forms.EmployeerForm(request.POST,request.FILES,instance = employeer)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(reverse("app:show"))
            except:
                print(form.errors)
    else:
        form = forms.EmployeerForm(instance = employeer)
        return render(request,"update.html",{'form':form})

def delete(request,id):
    employeer = models.Employeer.objects.get(id=id)
    employeer.delete()
    return HttpResponseRedirect(reverse("app:show"))

crudp/templates/employeer.html
<form method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">

</form>

crudp/templates/show.html
<center>
{% if employeers %}
<table border="2" cellspacing="0" cellpadding="10"> 
    <tr>
        <td>EID</td>
        <td>Ename</td>
        <td>EEmail</td>
        <td>Econtact</td>
        <td>EImage</td>
        <td colspan="2">Action</td>
    </tr>

    {% for emp in employeers %}
        <tr>
            <td>{{emp.eid}}</td>
            <td>{{emp.ename}}</td>
            <td>{{emp.eemail}}</td>
            <td>{{emp.econtact}}</td>
            <td> <img src="{{emp.eimage.url}}" alt="Employeer Image" height="200" width="200" /> </td>
            <td><a href="{% url 'app:update' emp.id %}">Edit</a></td>
            <td><a href="{% url 'app:delete' emp.id %}">Delete</a></td>
        </tr>
    {% endfor %}
</table>
{% else %}
    No Employeer Found
{% endif %}
<br><br>
<a href="{% url 'app:index' %}">Add New Employeer</a>
</center>

crudp/templates/update.html
<form method="post" enctype="multipart/form-data">

    {% csrf_token %}

    {{form.as_p}}
    <input type="submit" value="Update">
</form>